### PR TITLE
add support for latest Avalonia Build

### PR DESCRIPTION
**Pull request by laolarou726**
Avalonia Nightly Build changed several APIs (most of them are ready for the next preview release). This PR adds support for it.

### CODE REVIEW

**Comment by laolarou726** [comment]
For the removal of `IsEffectiveValueChange`: all changes that get as far as `PropertyChanged` will be effective value changes.

**Comment by SKProCH** [comment]
@laolarou726 did you think it should be merged asap, or I should wait till the next Avalonia preview will be released?

**Comment by laolarou726** [comment]
> @laolarou726 did you think it should be merged asap, or I should wait till the next Avalonia preview will be released? 

I think either is ok? You can wait till next preview release. Currently I'm linking the source code directly.

**Comment by laolarou726** [comment]
Just did more fix for the project

**Comment by SKProCH** [comment]
Oh, okay, thanks. I think what i need to add .editorconfig to the project to stabilize all formatting rules for code. What do you think?

**Comment by laolarou726** [comment]
> Oh, okay, thanks. I think what i need to add .editorconfig to the project to stabilize all formatting rules for code. What do you think?

Agree, currently I'm using the default lint rules in Resharper.

**Comment by laolarou726** [comment]
@SKProCH It seems you forgot to publish a release for this merge. Can you create a new release on Nuget? Thanks!

**Comment by SKProCH** [comment]
Oh, in current project releases are triggered by tag... So, yes, my fault. I launched pipeline. Thanks, @laolarou726 )

**Comment by SKProCH** [comment]
I should unify all scripts in my libraries...

**Pull request merged**
