### PR TITLE
replace all IBitmap to Bitmap

### PR DESCRIPTION
**Pull request by afunc233**
https://github.com/AvaloniaUtils/AsyncImageLoader.Avalonia/issues/11#issue-1720011211

### CODE REVIEW

**Comment by afunc233** [comment]
@SKProCH  hello , is this PR useless

**Comment by SKProCH** [comment]
Hello, @afunc233 

No, it useful, i think, but i plan merge it when new version of Avalonia with IBitmap changes released.

**Comment by afunc233** [comment]
it is compatible with avalonia11 , and the avalonia version has no change

**Comment by SKProCH** [comment]
Hmm, okay, i'll merge it in the weekends. Thanks!

**Review by SKProCH — APPROVED** [review]

**Pull request merged**
