### PR TITLE
add support for latest Avalonia Build

### PR DESCRIPTION
**Pull request by laolarou726**
Avalonia Nightly Build changed several APIs (most of them are ready for the next preview release). This PR adds support for it.

### CODE REVIEW

**Comment by SKProCH** [comment]
Hello, @laolarou726 
This is for Avalonia 11 preview 9?

**Comment by laolarou726** [comment]
> Hello, @laolarou726 
> 
> This is for Avalonia 11 preview 9?

I'm using latest nightly for this one. Because I noticed when I update my main project to latest nightly, this package stop working.

**Comment by laolarou726** [comment]
@SKProCH Just updated Avalonia 11.0.0 RC1.1! This should be ready for release.

**Comment by SKProCH** [comment]
Hm, why you removed HamburgerMenu, @laolarou726 ?

**Comment by laolarou726** [comment]
> Hm, why you removed HamburgerMenu, @laolarou726 ?

It broke when I updated to the latest Avalonia, so I just simply removed them.

**Comment by SKProCH** [comment]
Should be published as `3.0.0-avalonia11-preview6`. Thanks.

**Pull request closed without merging**
